# Project Information
site_name: OperatingSystem-2023

# Repository
repo_name: 'AzurIce/OperatingSystem-2023'
repo_url: 'https://github.com/AzurIce/OperatingSystem-2023'
edit_uri: edit/master/docs/

# Contents
nav:
  - 关于: "index.md"
  - 重构版实验手册: "重构版实验手册/index.md"
  - 实验:
    - 实验0 - 配置环境: "exp0-env-configuration.md"
    - 实验1 - 独立的可执行程序: "exp1-independent-application.md"
    - 实验2 - 裸机环境和最小化内核: "exp2-bare-metal-env-and-minimum-core.md"
    - 实验3 - 批处理和特权级: "exp3-batch-and-privilege.md"
    - 实验4 - 多道程序和协作式操作系统: "exp4-multiprogramming-and-cooperative-multitasking"
    - 实验4 - 多道程序和协作式操作系统: "exp5-multiprogramming-and-time-sharing.md"

extra_javascript:
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - js/diagram.js

extra_css:
  - css/diagram.css

# Theme
theme: 
  language: zh
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - toc.follow

markdown_extensions:
  # Images https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic # critic markup
  - pymdownx.caret # ^^insert^^ ^superscript^
  - pymdownx.mark  # ==mark==
  - pymdownx.tilde # ~~delete~~ ~subscript~
  - pymdownx.keys  # ++key++
  - admonition
  - pymdownx.details # collapsible admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: table
      anchor_linenums: true
  - pymdownx.blocks.tab:
      alternate_style: true
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - glightbox # image zoom (mkdocs-glightbox)
  - git-revision-date-localized: # (mkdocs-git-revision-date-localized-plugin)
      type: iso_datetime
      enable_creation_date: true
      fallback_to_build_date: true
